name: Feature request
description: Propose an improvement
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user pain does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
